import { Employee, Gift, BirthdayRecord, GiftHistory } from '@/src/types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    department: 'Engineering',
    position: 'Senior Developer',
    dateOfBirth: '1990-01-29',
    joinDate: '2021-03-15',
    phone: '+1 234 567 8901',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    department: 'Marketing',
    position: 'Marketing Manager',
    dateOfBirth: '1988-01-29',
    joinDate: '2020-07-22',
    phone: '+1 234 567 8902',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@company.com',
    department: 'Design',
    position: 'UX Designer',
    dateOfBirth: '1992-02-14',
    joinDate: '2022-01-10',
    phone: '+1 234 567 8903',
  },
  {
    id: '4',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    department: 'HR',
    position: 'HR Specialist',
    dateOfBirth: '1985-03-22',
    joinDate: '2019-09-01',
    phone: '+1 234 567 8904',
  },
  {
    id: '5',
    name: 'Amanda Foster',
    email: 'amanda.foster@company.com',
    department: 'Finance',
    position: 'Financial Analyst',
    dateOfBirth: '1991-04-05',
    joinDate: '2021-11-20',
    phone: '+1 234 567 8905',
  },
  {
    id: '6',
    name: 'David Kim',
    email: 'david.kim@company.com',
    department: 'Engineering',
    position: 'DevOps Engineer',
    dateOfBirth: '1993-05-18',
    joinDate: '2022-06-15',
    phone: '+1 234 567 8906',
  },
  {
    id: '7',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@company.com',
    department: 'Sales',
    position: 'Sales Executive',
    dateOfBirth: '1989-06-30',
    joinDate: '2020-02-28',
    phone: '+1 234 567 8907',
  },
  {
    id: '8',
    name: 'Robert Martinez',
    email: 'robert.martinez@company.com',
    department: 'Operations',
    position: 'Operations Manager',
    dateOfBirth: '1987-07-12',
    joinDate: '2018-04-10',
    phone: '+1 234 567 8908',
  },
];

export const mockGifts: Gift[] = [
  {
    id: '1',
    name: 'Amazon Gift Card',
    description: '$50 Amazon Gift Card',
    available: true,
    category: 'Gift Cards',
  },
  {
    id: '2',
    name: 'Spa Day Voucher',
    description: 'Full day spa treatment at luxury spa',
    available: true,
    category: 'Experience',
  },
  {
    id: '3',
    name: 'Premium Headphones',
    description: 'Sony WH-1000XM5 Wireless Headphones',
    available: false,
    category: 'Electronics',
  },
  {
    id: '4',
    name: 'Extra Day Off',
    description: 'One additional paid day off',
    available: true,
    category: 'Time Off',
  },
  {
    id: '5',
    name: 'Restaurant Voucher',
    description: '$100 fine dining experience',
    available: true,
    category: 'Gift Cards',
  },
  {
    id: '6',
    name: 'Fitness Subscription',
    description: '3-month gym membership',
    available: true,
    category: 'Wellness',
  },
  {
    id: '7',
    name: 'Movie Bundle',
    description: 'Cinema tickets + popcorn combo for 2',
    available: true,
    category: 'Entertainment',
  },
  {
    id: '8',
    name: 'Book Bundle',
    description: 'Choice of 3 bestselling books',
    available: true,
    category: 'Education',
  },
];

export const mockBirthdayRecords: BirthdayRecord[] = [
  {
    id: '1',
    employeeId: '1',
    employee: mockEmployees[0],
    date: '2026-01-29',
    emailSent: true,
    emailSentAt: '2026-01-29T08:00:00Z',
    giftReceived: mockGifts[0],
    giftReceivedAt: '2026-01-29T10:30:00Z',
    spinCompleted: true,
    year: 2026,
  },
  {
    id: '2',
    employeeId: '2',
    employee: mockEmployees[1],
    date: '2026-01-29',
    emailSent: true,
    emailSentAt: '2026-01-29T08:00:00Z',
    spinCompleted: false,
    year: 2026,
  },
  {
    id: '3',
    employeeId: '3',
    employee: mockEmployees[2],
    date: '2026-02-14',
    emailSent: false,
    spinCompleted: false,
    year: 2026,
  },
];

export const mockGiftHistory: GiftHistory[] = [
  { employeeId: '1', giftId: '2', year: 2025 },
  { employeeId: '1', giftId: '4', year: 2024 },
  { employeeId: '2', giftId: '1', year: 2025 },
  { employeeId: '3', giftId: '5', year: 2025 },
];
